### ISSUE TITLE
Complaints Tracker

### ISSUE THREAD

**Issue by vultuk** [ChiefSupportSystems/ChiefSupportSystems#21]
Complaints / EOD tracker or dashboard to be added to the system and linked to each case where   a complaint has been made.

- [x] Ability to create and edit Complaint Statuses (Per Domain)
- [x] Ability to view complaints on the front end
- [x] Ability to add complaints on the front end
- [x] Ability to pull a report of all complaints
- [x] **(Bonus)** Store a log of status change dates along with a note
- [x] **(Bonus)** Ability to assign a complaint to a user and add automatic tasks

**Comment by vultuk** [comment]
(Expression of Dis-satisfaction)

* Freetype
* List of Complaint Status
* First Response
* Final Response
* Report of all complaints
